<a href="https://colab.research.google.com/github/bsheese/cs377/blob/main/16_ml_intro/16_3_Intro_to_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducing Numpy Arrays

---

## Learning Objectives

After working through this notebook, you should be able to:

- Create NumPy arrays from lists, ranges, and built-in functions
- Perform vectorized operations and understand why they're faster than loops
- Index, slice, and use boolean masking to filter arrays
- Reshape arrays for use with scikit-learn models
- Use broadcasting to perform operations on arrays of different shapes
- Generate random data for simulations and train/test splits
- Compute summary statistics (mean, std, min, max, sum) on arrays

---


## Introduction
We are going to start using arrays quite a bit, specifically NumPy arrays. They work a lot like Python lists but with two key differences: every element must be the same type, and they support fast math operations on every element at once (no loops needed).

This notebook assumes you have seen Python lists before. The first section does a quick review so the contrast with arrays is clear.

## A Quick Review of Lists

Lists are structures used for storing data. In Python, lists can store any data type, including more lists, and lists can be changed in place (they are mutable). Lists can also be indexed, sliced, and iterated over. To briefly review:

In [126]:
# make an empty list
mylist = []
print('My empty list', mylist)

# add one thing to the list
mylist.append('A')
print('My appended list', mylist)

# add multiple things to the list
mylist.extend(['B','C','D', 'E'])
print('My extended list', mylist)

My empty list []
My appended list ['A']
My extended list ['A', 'B', 'C', 'D', 'E']


In [127]:
# use the index to return an item
print('My indexed item', mylist[0])

# use slicing to return a list of multiple items
print('My sliced items', mylist[2:4])

My indexed item A
My sliced items ['C', 'D']


In [128]:
# use the step function
print('Stepping through my list', mylist[::2])

# use the step function, but backwards
print('My backwards list', mylist[::-1])

Stepping through my list ['A', 'C', 'E']
My backwards list ['E', 'D', 'C', 'B', 'A']


In [129]:
# iterate through the list
for item in mylist:
  print(item+'!')

A!
B!
C!
D!
E!


In [130]:
# make an alias for mylist
# doesn't create anything new just an additional name for the same thing
notacopy_list = mylist
print('copylist and mylist contains the same values:', notacopy_list == mylist)
print('notacopylist and mylist are the same object with different names:', notacopy_list is mylist)


copylist and mylist contains the same values: True
notacopylist and mylist are the same object with different names: True


In [131]:
# compare this to the previous code cell
# make new copy of list, rather than just an alias that refers to the original
copylist = mylist[:] # notice we are slicing from beginning to end
print('copylist and mylist contains the same values:', copylist == mylist)
print('copylist and mylist are the same object with different names:', copylist is mylist)

copylist and mylist contains the same values: True
copylist and mylist are the same object with different names: False


## Introducing Numpy Arrays
Numpy arrays are a lot like lists in many ways. You can store data in them, change them, index them, slice them, and iterate through them.

In [132]:
# this is the standard import for numpy
import numpy as np

# make mylist into a numpy array
str_array = np.asarray(mylist)
print('My array', str_array)

# index my array
print('My indexed item', str_array[4])

# slice my array
print('My sliced array', str_array[2:4])

My array ['A' 'B' 'C' 'D' 'E']
My indexed item E
My sliced array ['C' 'D']


In [133]:
# my changed array, indexing the fourth item and changing it to 'Z'
str_array[4] = '9'
print('My changed item', str_array[4])
print('My changed arrayitem', str_array)

# appending is a bit different, it creates a new array
my_second_array = np.arange(1,6)
my_combined_arrays = np.append(str_array, my_second_array)
print('My appended arrays', my_combined_arrays)

My changed item 9
My changed arrayitem ['A' 'B' 'C' 'D' '9']
My appended arrays ['A' 'B' 'C' 'D' '9' '1' '2' '3' '4' '5']


But there is one thing you can do with a list that you can't do with an array: mix data types freely. Arrays enforce a single dtype for all elements, which is what makes them fast, but this also means that NumPy arrays are strictly homogeneous. Every single element must be the exact same data type (e.g., int64, float64, or str). If you try to insert a different type into an array, NumPy will automatically "coerce" (cast or convert) it to fit.

In [167]:
# Create an integer array
nums = np.array([1, 2, 3, 4, 5], dtype=int)
print('Original dtype:', nums.dtype)

# Assign a float to one element, the float is cast to an int
nums[0] = 9.99
print('After float assignment:', nums)
print('New dtype:', nums.dtype)



Original dtype: int64
After float assignment: [9 2 3 4 5]
New dtype: int64
After float appended: [9.   2.   3.   4.   5.   9.99]
New dtype: float64


In [ ]:
# Append float to one element, the array is cast to all ints
nums = np.append(nums, 9.99)
print('After float appended:', nums)
print('New dtype:', nums.dtype)

The fact that all the elements in the array are required to be the same datatype, means that certain types of computations can be done faster. For this reason, numpy arrays are common in mathematical and scientific applications.

Notice in the demo above that `9.99` was silently truncated to `9` when assigned to an integer array. This is a common source of bugs. If you accidentally assign a float to an integer array, you'll lose decimal precision without any warning. Always check your array dtype when working with mixed numeric types.

Numpy arrays also have a lot of functionality built into them that will come in handy for us.

In [135]:
# we have a traditional list
mylist = [1,2,3,4,5]

# we have a numpy array
myarray = np.array([1,2,3,4,5])

# we can add 4 to each value in the array
print(myarray + 4)

[5 6 7 8 9]


In [136]:
# we cannot add 4 to each value in the list in the same way,
# this will produce an error
try:
    print(mylist + 4)
except TypeError as e:
    print('Error:', e)

Error: can only concatenate list (not "int") to list


In [137]:
# we can subtract 5 from each value in the array
print(myarray - 5)

# but again, this will produce an error
# print(mylist - 5)

[-4 -3 -2 -1  0]


In [138]:
# this will multiply each value in the array by 4
print(myarray * 4)

# this will repeat the list four times
print(mylist * 4)

[ 4  8 12 16 20]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [139]:
# this will divide each value in the array by 2
print(myarray / 2)

# this will produce an error
# print(mylist / 2)

[0.5 1.  1.5 2.  2.5]


## Boolean Indexing: Filtering Arrays

One of the most powerful NumPy features: use conditions to filter arrays without loops.


In [140]:
# In the previous notebook, our song dataset used tempo and energy columns.
# Those columns are just NumPy arrays under the hood:
tempos = np.array([120, 95, 145, 130, 110])
energies = np.array([0.8, 0.3, 0.9, 0.7, 0.5])

# Find all high-tempo songs (tempo > 120)
high_tempo_mask = tempos > 120
print('Boolean mask:', high_tempo_mask)

# Use the mask to filter
high_tempo = tempos[high_tempo_mask]
print('High tempo songs:', high_tempo)

# Combine conditions with & (and) and | (or)
# High tempo AND high energy
intense = tempos[(tempos > 120) & (energies > 0.6)]
print('Intense songs:', intense)

# Count how many meet criteria
print(f'{high_tempo_mask.sum()} songs are high-tempo')

Boolean mask: [False False  True  True False]
High tempo songs: [145 130]
Intense songs: [145 130]
2 songs are high-tempo


## Multi-Dimensional Arrays

Every array we've built so far came from a single, flat list, like `mylist = [1, 2, 3, 4, 5]`. That's a **1D array**: one row of values. But NumPy arrays aren't limited to one dimension. Just as `np.array()` turned a list into a 1D array, it can turn a list of lists into a **2D array**, where each inner list becomes a row.

Think of a 1D array as a single column of numbers, and a 2D array as a small spreadsheet: rows and columns of numbers, all still sharing the same dtype. The `.shape` attribute tells you how many rows and columns an array has — `(5,)` for a 1D array of 5 values, `(2, 3)` for a 2D array with 2 rows and 3 columns.</cell id="D6rZRZQOj-Yf">


In [ ]:
# a 2D array built from a list of lists -- each inner list becomes a row
grid = np.array([[1, 2, 3],
                  [4, 5, 6]])
print(grid)
print('Shape:', grid.shape)  # (2, 3): 2 rows, 3 columns

Now that we've seen arrays with more than one dimension, what happens when we try to do math between two arrays that don't share the same shape? A `(2, 3)` array and a `(3,)` array clearly aren't the same shape, but NumPy can still combine them in useful ways. That's the idea behind **broadcasting**.

## Broadcasting in Numpy

**Broadcasting in NumPy** allows operations between arrays of different shapes by automatically expanding the smaller array so they share compatible dimensions.

**The One Golden Rule**

NumPy compares array shapes **from right to left** (starting at the trailing dimensions). Two dimensions are compatible if and only if:

* They are **equal**, or
* One of them is **1**

If these conditions are met for every dimension pair, broadcasting works. Otherwise, NumPy raises a `ValueError`.

---

**Common Shape Examples**

| Shape A | Shape B | Compatible? | Resulting Shape | Why It Works / Fails |
| --- | --- | --- | --- | --- |
| `(3, 4)` | `5` (scalar) | **Yes** | `(3, 4)` | Scalars stretch to fit any array shape. |
| `(3, 1)` | `(3,)` | **Yes** | `(3, 3)` | Right-to-left match: `1` expands to `3`, so `(3, 1)` and `(3,)` expand together. |
| `(4, 3)` | `(3,)` | **Yes** | `(4, 3)` | Right-to-left match: trailing `3`s match; missing outer dimension acts as `1`. |
| `(3,)` | `(4,)` | **No** | *Error* | Trailing dimensions `3` and `4` do not match, and neither is `1`. |

---

**Step-by-Step Visual Alignment**

When working through broadcasting problems, align the shapes to the right:

* **Example 1: Compatible**
```text
Array A shape:  4  x  3
Array B shape:        3  (treated as 1 x 3)
                ↓     ↓
Result shape:   4  x  3  (Success!)

```


* **Example 2: Incompatible**
```text
Array A shape:  3
Array B shape:  4
                ↓
           (3 ≠ 4, neither is 1 → Fails!)

```

## Broadcasting: Operations on Different Shapes

When you write `tempos + 5`, NumPy "broadcasts" the scalar `5` to match the shape of `tempos` before adding. Broadcasting generalizes to pairs of arrays using one rule:

> **Two dimensions are compatible when they are equal, or one of them is 1.**

NumPy compares shapes from the right. A shape of `(3,)` and a shape of `(3, 1)` are compatible; a shape of `(3,)` and `(4,)` are not.

In [141]:
# Scalar broadcasting: the scalar is stretched to match the array shape
broadcast_arr = np.array([1, 2, 3])
print('Original shape:', broadcast_arr.shape)   # (3,)
print('Scalar broadcast (+10):', broadcast_arr + 10)  # [11, 12, 13]

# 1D array broadcasting: two 1D arrays of equal length add element-wise (no stretching needed)
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print('\nElement-wise add:', a + b)  # [11, 22, 33]

# 2D broadcasting: a (3,1) column and a (3,) row broadcast to a (3,3) result
# NumPy stretches the column across 3 columns and the row across 3 rows
col = np.array([[1], [2], [3]])  # shape (3, 1)
row = np.array([10, 20, 30])     # shape (3,) — treated as (1, 3)
result = col + row               # broadcasts to shape (3, 3)
print('\ncol shape:', col.shape, '  row shape:', row.shape, '  result shape:', result.shape)
print(result)
# [[11, 21, 31],
#  [12, 22, 32],
#  [13, 23, 33]]

Original shape: (3,)
Scalar broadcast (+10): [11 12 13]

Element-wise add: [11 22 33]

col shape: (3, 1)   row shape: (3,)   result shape: (3, 3)
[[11 21 31]
 [12 22 32]
 [13 23 33]]


## Creating Arrays
Here are some methods for generating new arrays.

In [142]:
# create numpy array from python list
mylist = [1, 2, 3, 4, 5]
np.array(mylist)

array([1, 2, 3, 4, 5])

In [143]:
# create numpy array from list via range (range returns a range object that is much like a list)
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [144]:
# alternatively use numpy's built in 'arange' method
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [145]:
# start, end, step
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [146]:
# start, end, step
np.arange(18, 0, -2)

array([18, 16, 14, 12, 10,  8,  6,  4,  2])

## A Few Handy Numpy Array Methods for Stats

`min`, `max`, `mean`, `std`, and `sum` are methods on any NumPy array. `mean` gives the average, `std` measures the spread (how far values scatter from the mean), and `sum` totals all elements.

In [147]:
# Compute basic statistics on our song data
print('Tempo stats:')
print('  Min:', tempos.min(), 'BPM')
print('  Max:', tempos.max(), 'BPM')
print('  Mean:', tempos.mean(), 'BPM')
print('  Std (spread):', tempos.std(), 'BPM')
print()
print('Energy stats:')
print('  Min:', energies.min())
print('  Max:', energies.max())
print('  Mean:', energies.mean())
print('  Std (spread):', energies.std())
print()
print('Total energy across all songs:', energies.sum())

Tempo stats:
  Min: 95 BPM
  Max: 145 BPM
  Mean: 120.0 BPM
  Std (spread): 17.029386365926403 BPM

Energy stats:
  Min: 0.3
  Max: 0.9
  Mean: 0.64
  Std (spread): 0.2154065922853802

Total energy across all songs: 3.2


## A Brief Exercise

In [148]:
# execute this first
a1 = np.arange(0,1000,2)
a2 = np.arange(1,11)

Complete the function `array_problem1()` below, which takes two arrays as arguments. The function should:
* add 4 to every value in `a1`
* multiply every value in `a2` by five
* append `a1` to the end of `a2` (use `np.append(a2, a1)`) and store the result
* create a slice of the combined array containing only the first 50 values
* return the sum of all of the array values

**Note:** This exercise uses `np.append()` for practice. In real code with large datasets, preallocate arrays instead (see the next section).

In [149]:
def array_problem1(array1, array2):
  pass  # enter and test your code here


In [150]:
# call your function and check the result, it should be 1995
array_problem1(a1, a2)

In [151]:
# @title Show Solution

print('''
def array_problem1(array1, array2):
    a1_modified = array1 + 4
    a2_modified = array2 * 5
    combined = np.append(a2_modified, a1_modified)
    first_50 = combined[:50]
    return first_50.sum()

print('Solution result:', array_problem1(a1, a2))  # Should be 1995
''')


def array_problem1(array1, array2):
    a1_modified = array1 + 4
    a2_modified = array2 * 5
    combined = np.append(a2_modified, a1_modified)
    first_50 = combined[:50]
    return first_50.sum()

print('Solution result:', array_problem1(a1, a2))  # Should be 1995



## Avoid Repeated Appending
Appending once to an array (as you did in the exercise above) is fine. But appending in a loop is slow: each call to `np.append` creates an entirely new array, copying all existing data. If you know the final size ahead of time, it's faster to preallocate with `np.zeros` or `np.ones` and then fill in the values.

In [152]:
# Instead of this (slow for large loops):
result = np.array([])
for i in range(5):
    result = np.append(result, i)

# Do this (preallocate, then fill):
result = np.zeros(5)
for i in range(5):
    result[i] = i

print('Preallocated result:', result)

Preallocated result: [0. 1. 2. 3. 4.]


## More Ways to Create Arrays

Beyond `np.array()` and `np.arange()`, NumPy provides several functions that create arrays filled with a specific value or evenly spaced numbers. These come up constantly in ML for initializing weights, generating test inputs, and spacing out parameter grids.

In [153]:
# array of zeros
zeros_arr = np.zeros(5)
print(zeros_arr)

# array of ones
ones_arr = np.ones(5)
print(ones_arr)

# array filled with a constant value
filled_arr = np.full(5, 42)
print(filled_arr)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[42 42 42 42 42]


In [154]:
# np.linspace: evenly spaced values between start and stop (inclusive)
# Unlike arange (which steps by a fixed amount), linspace fixes the number of points
linspace_arr = np.linspace(0, 100, 3)
print(linspace_arr)   # [  0.  50. 100.]

# Useful when you need exactly N points — here, 11 values from 0 to 100
linspace_fine = np.linspace(0, 100, 11)
print(linspace_fine)  # [  0.  10.  20. ... 100.]

[  0.  50. 100.]
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


## Creating Multi-Dimensional Arrays

In [155]:
zeros_2d = np.zeros(shape=(3,3))
print(zeros_2d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [156]:
ones_2d = np.ones(shape=(5,2))
print(ones_2d)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [157]:
matrix_2d = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(matrix_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [158]:
# you can check your array's dimensions using the shape attribute
# this will also work with pandas objects, which we will see later
matrix_2d.shape

(3, 4)

### Try It: Multi-Dimensional Arrays
Create a 3x3 array filled with 1s, then use indexing to change the center element (row 1, column 1) to 99.

In [159]:
# your code here -- fill in the blanks, then uncomment the lines and run
# arr = np.ones(...)       # create a 3x3 array of ones
# arr[..., ...] = 99       # change the center element to 99
# print(arr)

In [160]:
# @title Show Solution

print('''
# Solution
arr = np.ones((3, 3))
arr[1, 1] = 99
print(arr)
''')


# Solution
arr = np.ones((3, 3))
arr[1, 1] = 99
print(arr)



## Multi-Dimensional Indexing and Slicing

Accessing elements in 2D arrays uses `[row, column]` syntax. You can slice along each dimension independently.


In [161]:
idx_matrix = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

print('Element at row 1, col 2:', idx_matrix[1, 2])  # 6
print('First row:', idx_matrix[0])
print('First column:', idx_matrix[:, 0])
print('Bottom-right 2x2 subgrid:', idx_matrix[1:, 1:])

Element at row 1, col 2: 6
First row: [1 2 3]
First column: [1 4 7]
Bottom-right 2x2 subgrid: [[5 6]
 [8 9]]


## Reshaping Arrays

Many scikit-learn functions expect 2D input (samples x features), but you often have 1D data. `reshape()` changes array dimensions without copying data.


In [162]:
# 1D array of house sizes
sqft = np.array([1200, 1500, 1800, 2200])
print('Original shape:', sqft.shape)  # (4,)

# Reshape to 2D: 4 samples, 1 feature each
sqft_2d = sqft.reshape(-1, 1)
print('\nReshaped shape:', sqft_2d.shape)  # (4, 1)
print(sqft_2d)

# The -1 means "infer this dimension automatically"
# reshape(4, 1) would work too, but -1 is more flexible

# Reshape to different configurations
reshape_src = np.arange(12)
print('\n1D:', reshape_src)
print('\nReshaped to 3x4:', reshape_src.reshape(3, 4))
print('\nReshaped to 2x6:', reshape_src.reshape(2, 6))

Original shape: (4,)

Reshaped shape: (4, 1)
[[1200]
 [1500]
 [1800]
 [2200]]

1D: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped to 3x4: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to 2x6: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


## Random Number Generation

Essential for ML: creating synthetic data, train/test splits, and model initialization.


In [163]:
np.random.seed(42)  # For reproducible results

# Random integers
print('Random ints:', np.random.randint(0, 100, 5))

# Random floats
print('\nRandom floats:', np.random.random(5))

# Normal distribution (mean=0, std=1)
print('\nNormal distribution:', np.random.normal(0, 1, 5))

# Shuffle an array
shuffle_arr = np.arange(10)
np.random.shuffle(shuffle_arr)
print('\nShuffled:', shuffle_arr)

# Random choice
print('\nRandom choice:', np.random.choice(['A', 'B', 'C'], 3))

Random ints: [51 92 14 71 60]

Random floats: [0.59685016 0.44583275 0.09997492 0.45924889 0.33370861]

Normal distribution: [ 0.39257975 -0.92918467  0.07983181 -0.1595165   0.02222183]

Shuffled: [1 5 4 8 0 7 6 3 2 9]

Random choice: ['C' 'A' 'A']


You can read more about numpy basics here: [NumPy Absolute Beginners Guide](https://numpy.org/doc/stable/user/absolute_beginners.html)

## Your Turn

Use the `tempos` and `energies` arrays defined earlier in this notebook to answer the following.

**Exercise 1:** Create a boolean mask for songs with energy above 0.6. How many songs qualify?

**Exercise 2:** Using `tempos`, compute the mean and standard deviation. Then create a new array where each value is the tempo normalized to z-score form: `(tempo - mean) / std`. Print the result.

**Exercise 3:** Use `np.linspace` to create an array of 6 evenly spaced BPM values between 80 and 160. Then use broadcasting to add 10 BPM to every value.

In [164]:
# @title Show Answers

energy_masked = energies[energies >.6]
print('''
# Exercise 1
energy_masked = energies[energies >.6]
energy_masked.size
''')
print(f'How many songs qualify: {energy_masked.size}')



tempos_mean = tempos.mean()
tempos_std = tempos.std()
tempos_zscore = (tempos - tempos_mean)/tempos_std

print('''
# Exercise 2
tempos_mean = tempos.mean()
tempos_std = tempos.std()
tempos_zscore = (tempos - tempos_mean)/tempos_std
''')
print(f'tempos zscores: {tempos_zscore}')



bpm = np.linspace(80, 160, 6)
bpm = bpm + 10
print('''
# Exercise 3:
bpm = np.linspace(80, 160, 6)
bpm = bpm + 10
''')
print(f'New bpm = {bpm}')


# Exercise 1
energy_masked = energies[energies >.6]
energy_masked.size

How many songs qualify: 3

# Exercise 2
tempos_mean = tempos.mean()
tempos_std = tempos.std()
tempos_zscore = (tempos - tempos_mean)/tempos_std

tempos zscores: [ 0.         -1.46805055  1.46805055  0.58722022 -0.58722022]

# Exercise 3:
bpm = np.linspace(80, 160, 6)
bpm = bpm + 10

New bpm = [ 90. 106. 122. 138. 154. 170.]


---
Now that we've covered the basics of arrays, the next notebook introduces Pandas Series. Series are a core data structure we'll use throughout the course.

<a href="16_4_Pandas_Series.ipynb">Continue to: Introduction to Pandas Series →</a>